"""empty message

Revision ID: 86210f63ad43
Revises: 
Create Date: 2023-10-02 21:26:39.354347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86210f63ad43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AREA', sa.Integer(), nullable=True),
    sa.Column('AREA_TITLE', sa.Text(), nullable=True),
    sa.Column('AREA_TYPE', sa.Integer(), nullable=True),
    sa.Column('PRIM_STATE', sa.Text(), nullable=True),
    sa.Column('NAICS', sa.Text(), nullable=True),
    sa.Column('NAICS_TITLE', sa.Text(), nullable=True),
    sa.Column('I_GROUP', sa.Text(), nullable=True),
    sa.Column('OWN_CODE', sa.Integer(), nullable=True),
    sa.Column('OCC_CODE', sa.Text(), nullable=True),
    sa.Column('OCC_TITLE', sa.Text(), nullable=True),
    sa.Column('O_GROUP', sa.Text(), nullable=True),
    sa.Column('TOT_EMP', sa.Integer(), nullable=True),
    sa.Column('EMP_PRSE', sa.Float(), nullable=True),
    sa.Column('JOBS_1000', sa.Float(), nullable=True),
    sa.Column('LOC_QUOTIENT', sa.Float(), nullable=True),
    sa.Column('PCT_TOTAL', sa.Float(), nullable=True),
    sa.Column('PCT_RPT', sa.Float(), nullable=True),
    sa.Column('H_MEAN', sa.Float(), nullable=True),
    sa.Column('A_MEAN', sa.Integer(), nullable=True),
    sa.Column('MEAN_PRSE', sa.Float(), nullable=True),
    sa.Column('H_PCT10', sa.Float(), nullable=True),
    sa.Column('H_PCT25', sa.Float(), nullable=True),
    sa.Column('H_MEDIAN', sa.Float(), nullable=True),
    sa.Column('H_PCT75', sa.Float(), nullable=True),
    sa.Column('H_PCT90', sa.Float(), nullable=True),
    sa.Column('A_PCT10', sa.Integer(), nullable=True),
    sa.Column('A_PCT25', sa.Integer(), nullable=True),
    sa.Column('A_MEDIAN', sa.Integer(), nullable=True),
    sa.Column('A_PCT75', sa.Integer(), nullable=True),
    sa.Column('A_PCT90', sa.Integer(), nullable=True),
    sa.Column('ANNUAL', sa.Float(), nullable=True),
    sa.Column('HOURLY', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
